# Generated by Django 4.2.4 on 2023-09-03 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cria_lista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastraItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cria_lista.crialista')),
            ],
        ),
    ]
