# Generated by Django 4.2.4 on 2023-09-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cria_lista', '0004_alter_cadastraitens_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='crialista',
            name='meta_de_gastos',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=6),
        ),
    ]
