# Generated by Django 4.2.4 on 2023-09-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cria_lista', '0005_crialista_meta_de_gastos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDeItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Prioritários', 'Prioritários'), ('Secundários', 'Secundários'), ('Luxo', 'Luxo')], max_length=20)),
            ],
        ),
    ]
