# Generated by Django 4.2.4 on 2023-09-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cria_lista', '0009_alter_cadastraitens_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastraitens',
            name='tipo',
        ),
    ]
