# Generated by Django 4.2.4 on 2023-09-10 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cria_lista', '0013_alter_cadastraitens_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='crialista',
            name='tipo',
            field=models.CharField(choices=[('Prioritários', 'Prioritários'), ('Secundários', 'Secundários'), ('Luxo', 'Luxo')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastraitens',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_de_itens', to='cria_lista.crialista'),
        ),
        migrations.DeleteModel(
            name='TiposDeItens',
        ),
    ]
