# Generated by Django 4.2.4 on 2023-09-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cria_lista', '0014_crialista_tipo_alter_cadastraitens_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastraitens',
            name='lista',
        ),
        migrations.RemoveField(
            model_name='cadastraitens',
            name='tipo',
        ),
    ]
