# Generated by Django 4.2.4 on 2023-09-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cria_lista', '0015_remove_cadastraitens_lista_remove_cadastraitens_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Prioritários', 'Prioritários'), ('Secundários', 'Secundários'), ('Luxo', 'Luxo')], max_length=50)),
                ('categoria', models.CharField(choices=[('compras-do-mes', 'Compras do mês.'), ('transporte', 'Transporte.'), ('lazer', 'Lazer.'), ('alimentacao-fora', 'Alimentação fora de casa.')], max_length=50)),
                ('data', models.DateField()),
                ('meta_de_gastos', models.DecimalField(decimal_places=2, default=500, max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='CriaLista',
        ),
    ]
