# Generated by Django 4.2.4 on 2023-09-11 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cria_lista', '0016_lista_delete_crialista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='CadastraItens',
        ),
        migrations.AlterField(
            model_name='lista',
            name='categoria',
            field=models.CharField(choices=[('compras-do-mes', 'Compras do mês'), ('transporte', 'Transporte'), ('lazer', 'Lazer'), ('alimentacao-fora', 'Alimentação fora de casa')], max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_lista', to='cria_lista.lista'),
        ),
    ]
