# Generated by Django 4.2.4 on 2023-09-11 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cria_lista', '0017_item_delete_cadastraitens_alter_lista_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista', to='cria_lista.lista'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='categoria',
            field=models.CharField(choices=[('Compras do mês', 'Compras do mês'), ('Transporte', 'Transporte'), ('Lazer', 'Lazer'), ('Alimentação fora de casa', 'Alimentação fora de casa')], max_length=50),
        ),
    ]
