# Generated by Django 4.2.5 on 2023-09-20 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cria_lista', '0019_item_quantidade_alter_item_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cria_lista.lista'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='categoria',
            field=models.CharField(choices=[('Compras-do-mes', 'Compras do mês'), ('Transporte', 'Transporte'), ('Lazer', 'Lazer'), ('Alimentacao-fora', 'Alimentação fora de casa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lista',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
