# Generated by Django 5.0.2 on 2024-06-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cria_lista', '0021_alter_lista_categoria_alter_lista_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
