# Generated by Django 5.2.4 on 2025-07-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cria_lista', '0022_item_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='tipo_categoria_gasto',
            field=models.CharField(choices=[('Prioritários', 'Prioritários'), ('Secundários', 'Secundários'), ('Luxo', 'Luxo'), ('Outros', 'Outros')], default='Outros', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lista',
            name='meta_de_gastos',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lista',
            name='tipo',
            field=models.CharField(choices=[('GASTO', 'Lista de Gastos'), ('DIVIDA', 'Lista de Dívidas')], default='GASTO', max_length=10),
        ),
    ]
